name: bikini
favicon: null
layout_spectrum: 0.9608322964049876
typography_spectrum: 0.5201750046107918
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.37304653436876833
  lightness: 0.5517704037483782
  saturation: 0.3745213760994375
  rhythmicContrast: 0.6064803376793861
purpose: []
